### PR TITLE
Added Event Driven Shield Button Press

### PR DESCRIPTION
**Pull request by JakeLardinois**
Soldering a wire to Pin20 (INTA) of the MCP23017 chip and then connecting it to to a digital pin (configured in code) on the Netduino enables button press events to be read without a loop.  The example code sets up GPIO_PIN_D10 as the interrupt pin and then changes the display in the event handler.  This functionality allows things such as Serial Port data received events to work in conjunction with the buttons and updating the LCD display

### CODE REVIEW

**Comment by giawa** [comment]
This is awesome, but requires a modification to the hardware - I think it would be best to maintain this as a branch and make a note of it in the README instead of merging it into master.  What are your thoughts?

**Comment by JakeLardinois** [comment]
Yeah, that is a better idea; then users could have more of a distinct choice...  
I'll modify the readme are you then going to reference it in Master?  
I was very grateful that you had published the repo!  So when I figured this out, I wanted to contribute back :)

**Comment by giawa** [comment]
Yup, that sounds good!  If you submit a pull request for the README referencing your branch I would be more than happy to include it.  I'm glad you found the code useful, and thanks for contributing back!

**Comment by JakeLardinois** [comment]
I added a branch to my repo that I forked from you.  I'll send a new pull request for the updated readme.md

**Pull request closed without merging**
